config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update', as: :update_task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group" id="check">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <div class="submit"><%= f.submit class: 'btn btn-primary' %></div>
<% end %>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>TASKS</h1>

<% @tasks.each do |task| %>

  <p><% if task.completed %></p>
  <h2><i class="far fa-check-square"><%= link_to task.title, task_path(task) %></i>
      <%= link_to task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } do %>
            <i class="fas fa-trash-alt"></i>
            <% end %>
          </h2>
      <% else  %>
  <h2><i class="far fa-square"><%= link_to task.title, task_path(task) %></i>
          <%= link_to task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
        </h2>
     <% end %>
<% end %>

<%= link_to "Create a new task", new_task_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="submit"><%= f.submit class: 'btn btn-primary' %></div>
<% end %>

app/views/tasks/show.html.erb
<%= link_to "Edit this task",tasks_path %>

<h1><%= @task.title %></h1>
<div class="details"> <%=  @task.details%></div>
 <div><% if @task.completed %>
  <p><i class="far fa-check-square"> This task is completed!</i></p>
      <% else  %>
  <p><i class="far fa-square"> This task is not completed yet.</i></p>
     <% end %>
  </div>

<%= link_to "Go back",tasks_path %>